//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioUsuario.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denuncias
    {
        public int numDenuncia { get; set; }
        public string tituloDenuncia { get; set; }
        public string detalleDenuncia { get; set; }
        public int latitudDenuncia { get; set; }
        public int longitudDenuncia { get; set; }
        public int idUsuario { get; set; }
        public int tipoDenuncia { get; set; }
        public System.DateTime fechaHoraDenuncia { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual TipoDenuncias TipoDenuncias { get; set; }
    }
}
