//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioUsuario.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perdidas
    {
        public int idPerdida { get; set; }
        public string tituloPerdida { get; set; }
        public string descripcionPerdida { get; set; }
        public int idUsuarioPerdida { get; set; }
        public string numeroUsuarioPerdida { get; set; }
        public string imagenPerdida { get; set; }
    }
}
