//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioUsuario.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string apellidoUsuario { get; set; }
        public string mail { get; set; }
        public string password { get; set; }
        public string fechaNacimiento { get; set; }
        public string direccionCasa { get; set; }
        public Nullable<double> latitudCasa { get; set; }
        public Nullable<double> longitudCasa { get; set; }
    }
}
